### ISSUE TITLE
publicPath支持function，但是validate里面只有string

### ISSUE THREAD

**Issue by chenhebing** [lamovv/assemblyscript-wasm-loader#1]
function支持
https://github.com/lamovv/assemblyscript-wasm-loader/blob/master/lib/index.js#L134
validate
https://github.com/lamovv/assemblyscript-wasm-loader/blob/master/lib/options.out.json#L15

期望将type string去掉

**Comment by chenhebing** [comment]
publicPath 支持function，但是大多数情况下 function获取publicPath是在运行时获取的，所以希望将publicPath()执行的时机放在前端

我做了些改动，亲测有效
![image](https://user-images.githubusercontent.com/12512045/85122819-c24ed080-b259-11ea-8928-5f3b9c3c9c12.png)
![image](https://user-images.githubusercontent.com/12512045/85122835-c844b180-b259-11ea-87c2-623c7d600c0e.png)

**Comment by lamovv** [comment]
嗯，已0.1.4版本搞定
